# SPDX-FileCopyrightText: 2026 Edward Kmett <ekmett@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
if(NOT CMAKE_GENERATOR MATCHES "^Ninja")
  message(FATAL_ERROR "The qualified module build requires Ninja or Ninja Multi-Config.")
endif()
if(FTZ_ENABLE_IPO)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT ftz_ipo_ok OUTPUT ftz_ipo_error LANGUAGES CXX)
  if(NOT ftz_ipo_ok)
    message(FATAL_ERROR "Requested IPO is unavailable: ${ftz_ipo_error}")
  endif()
endif()
function(ftz_host_settings target)
  target_compile_features(${target} PUBLIC cxx_std_26)
  target_compile_definitions(${target} PUBLIC FTZ_FP32_HARDWARE_FTZ=${FTZ_FP32_HARDWARE_FTZ})
  set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
  if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      message(FATAL_ERROR "The Windows host configuration requires clang-cl.")
    endif()
    target_compile_options(${target} PUBLIC /fp:strict)
    target_compile_options(${target} PRIVATE /W4 /clang:-Wno-unqualified-std-cast-call)
    if(FTZ_ENABLE_ASAN)
      target_compile_options(${target} PUBLIC /fsanitize=address)
      target_link_options(${target} PUBLIC /INCREMENTAL:NO)
    endif()
  else()
    target_compile_options(${target} PUBLIC -fno-fast-math -ffp-contract=off -frounding-math)
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wno-unqualified-std-cast-call)
    if(FTZ_ENABLE_ASAN)
      target_compile_options(${target} PUBLIC -fsanitize=address -fno-omit-frame-pointer)
      target_link_options(${target} PUBLIC -fsanitize=address)
    endif()
  endif()
  if(NOT FTZ_ENABLE_EXCEPTIONS)
    if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
      # /clang:-fno-exceptions does not override clang-cl /EHsc. Both language
      # unwind and MSVC STL modes must agree in producer and BMI consumers.
      target_compile_options(${target} PUBLIC /EHs-c-)
      target_compile_definitions(${target} PUBLIC _HAS_EXCEPTIONS=0)
    else()
      target_compile_options(${target} PUBLIC -fno-exceptions)
    endif()
  endif()
  if(FTZ_ENABLE_IPO)
    set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
  endif()
endfunction()

# CMake links clang-cl targets directly, so select the matching /MD ASan runtime
# from this compiler rather than silently borrowing an installed MSVC runtime.
function(ftz_link_clang_cl_asan target)
  if(NOT FTZ_ENABLE_ASAN)
    return()
  endif()
  if(NOT (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC"))
    return()
  endif()
  if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(AMD64|amd64|x86_64|X86_64)$")
    message(FATAL_ERROR "The clang-cl ASan helper currently supports Windows x64 only.")
  endif()
  execute_process(COMMAND "${CMAKE_CXX_COMPILER}" --print-runtime-dir
    OUTPUT_VARIABLE runtime_dir OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)
  file(TO_CMAKE_PATH "${runtime_dir}" runtime_dir)
  set(asan "${runtime_dir}/clang_rt.asan_dynamic-x86_64")
  set(thunk "${runtime_dir}/clang_rt.asan_dynamic_runtime_thunk-x86_64.lib")
  foreach(path "${asan}.lib" "${asan}.dll" "${thunk}")
    if(NOT EXISTS "${path}")
      message(FATAL_ERROR "Missing the selected clang-cl ASan runtime: ${path}")
    endif()
  endforeach()
  target_link_libraries(${target} PRIVATE "${asan}.lib")
  target_link_options(${target} PRIVATE "/wholearchive:${thunk}" /include:__asan_seh_interceptor /INCREMENTAL:NO)
  add_custom_command(TARGET ${target} POST_BUILD
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${asan}.dll" "$<TARGET_FILE_DIR:${target}>"
    VERBATIM)
endfunction()
