#pragma once
#include "ftz/config.h"
#include "ftz/math/approx.h"
#include "ftz/math/float.h"

// Altered coefficient use from SLEEF 3.9.0 atan2kf, under Boost 1.0 below.
// Our normalized division, serial FMA Horner, tiny mask, finite admission and
// bit quadrant folds define a separate graph, not SLEEF's accuracy contract.
namespace ftz { namespace detail { namespace math {
  struct atan2_result { unsigned int bits, valid; };
  struct atan2_value { float radians; unsigned int valid; };
  // All finite inputs are accepted except (signed-FTZ(y), signed-FTZ(x))=(0,0).
  template <bool Hardware = FTZ_FP32_HARDWARE_FTZ != 0>
  inline atan2_result atan2_words(unsigned int y, unsigned int x) {
    atan2_result result; result.bits=result.valid=0u;
    if (!approx_finite(y) || !approx_finite(x)) return result;
    y=approx_flush(y); x=approx_flush(x);
    unsigned int ay=y&0x7fffffffu, ax=x&0x7fffffffu;
    if ((ay|ax)==0u) return result;
    bool swap=ay>ax, negative_x=(x&0x80000000u)!=0u;
    if (ay==0u || ax==0u) {
      unsigned int magnitude=ax==0u ? 0x3fc90fdbu : (negative_x ? 0x40490fdbu : 0u);
      result.bits=magnitude|(y&0x80000000u); result.valid=1u;
      return result;
    }
    approx_result quotient=approx_divide(swap?ax:ay,swap?ay:ax);
    if (quotient.valid==0u) return result;
    // The true ratio is at most one. Remove possible reciprocal overshoot.
    unsigned int ratio_bits=quotient.bits>0x3f800000u ? 0x3f800000u : quotient.bits;
    bool tiny=ratio_bits<=0x39800000u;
    // Hardware mode may evaluate unobserved tiny stages.
    unsigned int masked=Hardware ? ratio_bits : (tiny?0u:ratio_bits);
    float ratio=fp32_decode(ratio_bits), t=fp32_decode(masked);
    float z=fp32_mul<false>(t,t);
    float h=fp32_decode(0x3b390ccdu);
    h=fp32_fma<false>(h,z,fp32_decode(0xbc82b80du));
    h=fp32_fma<false>(h,z,fp32_decode(0x3d2e19b6u));
    h=fp32_fma<false>(h,z,fp32_decode(0xbd995ffau));
    h=fp32_fma<false>(h,z,fp32_decode(0x3dd9ccf2u));
    h=fp32_fma<false>(h,z,fp32_decode(0xbe116f9fu));
    h=fp32_fma<false>(h,z,fp32_decode(0x3e4cb9a7u));
    h=fp32_fma<false>(h,z,fp32_decode(0xbeaaaa5du));
    float q=fp32_mul<false>(z,h);
    float angle=fp32_fma<false>(q,t,ratio);
    angle=fp32_decode(tiny?ratio_bits:fp32_encode(angle));
    if (swap) angle=fp32_fma<false>(-1.0f,angle,fp32_decode(0x3fc90fdbu));
    if (negative_x) angle=fp32_fma<false>(-1.0f,angle,fp32_decode(0x40490fdbu));
    result.bits=fp32_encode(angle)|(y&0x80000000u); result.valid=1u;
    return result;
  }
  template <bool Hardware = FTZ_FP32_HARDWARE_FTZ != 0>
  inline atan2_value atan2_checked(float y,float x) {
    atan2_result r=atan2_words<Hardware>(fp32_encode(y),fp32_encode(x));
    atan2_value result;result.radians=fp32_decode(r.bits);result.valid=r.valid;return result;
  }
}}}

/*
Copyright Naoki Shibata and contributors 2010 - 2025.
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * \file
 * \license
 * SPDX-FileType: SOURCE
 * SPDX-FileCopyrightText: 2010 - 2025 Naoki Shibata and contributors
 * SPDX-FileCopyrightText: 2026 Edward Kmett <ekmett@gmail.com>
 * SPDX-License-Identifier: BSL-1.0
 * \endlicense
 * \author Edward Kmett <ekmett@gmail.com>
 * \brief Finite atan2 with normalized division and a fixed Horner polynomial.
 */
